joint_limits:
  shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: true
    max_acceleration: 6.3
    has_jerk_limits: true
    max_jerk: 1000.0
  shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: true
    max_acceleration: 6.3
    has_jerk_limits: true
    max_jerk: 1000.0
  elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: true
    max_acceleration: 6.3
    has_jerk_limits: true
    max_jerk: 1000.0
  wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: true
    max_acceleration: 6.4
    has_jerk_limits: true
    max_jerk: 1000.0
  wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: true
    max_acceleration: 6.4
    has_jerk_limits: true
    max_jerk: 1000.0
  wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: true
    max_acceleration: 6.4
    has_jerk_limits: true
    max_jerk: 1000.0
