#!/usr/bin/env python3

# ROS2
import rclpy
from rclpy.node import Node
from sensor_msgs.msg import Image, PointCloud2, CameraInfo, Range
from std_msgs.msg import Int16MultiArray, Float32
from tf2_ros import TransformException
from tf2_ros.buffer import Buffer
from tf2_ros.transform_listener import TransformListener
from tf2_geometry_msgs import TransformStamped
from geometry_msgs.msg import Pose, PoseArray
from scipy.spatial.transform import Rotation as R
import sensor_msgs_py.point_cloud2 as pc2
from rclpy.qos import (QoSProfile,
    ReliabilityPolicy, HistoryPolicy, DurabilityPolicy,
)
from std_msgs.msg import Header

# Image processing
from cv_bridge import CvBridge
import cv2
import numpy as np


""" Class to handle publishing and subscribing of the data related to the gripper (camera, tof)
  Three basic modes: 
     1) Real data from the camera and tof 
          - attach to the hard ware and publish the data
     2) Fake data from a pre-saved point cloud
          - Project the point cloud into the camera frame to make an image
          - Project the depth values at the center to make a depth reading
     3) Fake data from a scene/Gazebo [TODO]
          - Render the fake trees to make an image
          - Render the depth values at the center to spoof the TOF reading
          
  Other data:
     - Point cloud rendering: if there is a point cloud (generated by the mast or base camera 
        - publish the point cloud rendering in a separate channel from the 'real' image
     - 3D apple locations: If the apple location service has generated 3D points
        - publish the 2D locations of those points at the same time as the rendered image (30fps)
        """
class GripperPalmCamera(Node):
    def __init__(self, resolution=(800, 600), target_fr=30):
        super().__init__("gripper_palm_camera_publisher")

        # For virtual camera or real one
        self.declare_parameter("use_fake_hardware", False)
        
        # If we're using fake hardware then only publish new image when end effector moves
        if self.get_parameter('use_fake_hardware').value:
            qos_profile = QoSProfile(reliability=ReliabilityPolicy.BEST_EFFORT,
                                                           durability=DurabilityPolicy.TRANSIENT_LOCAL,
                                                           history=HistoryPolicy.KEEP_LAST, depth=1)
        else:
            qos_profile = QoSProfile(reliability=ReliabilityPolicy.BEST_EFFORT,
                                     history=HistoryPolicy.KEEP_LAST,
                                     depth=3)
            
        # This is the real camera image (if there is one), otherwise it's the same as the projected point cloud image
        self.camera_pub = self.create_publisher(Image, "gripper/rgb_palm_camera/image_raw", qos_profile)
        # The point cloud from the rgbd camera (mast or base) projected onto the gripper camera
        self.proj_im_pub = self.create_publisher(Image, "gripper/rgb_palm_camera/image_proj", qos_profile)
        
        # cv bridge to convert to ros image msg
        self.bridge = CvBridge()

        # Note: If a real camera is defined, these will come from that
        self.declare_parameter("resolution", resolution)
        self.declare_parameter("target_frame_rate", 30)
        self.declare_parameter("source_frame", "mast_camera_color_optical_frame")

        # Note: If there is a real tof sensor, then this will be ignored
        self.declare_parameter("tof_angle", 15)
        self.tof_angle = np.pi * self.get_parameter("tof_angle").get_parameter_value().integer_value / 180.0

        # Real camera variables (which port to read from) 
        self.declare_parameter("palm_camera_device_num", 2)
        self.device = self.get_parameter("palm_camera_device_num").get_parameter_value().integer_value
        self.camera = None

        # Pressure sensors plus real tof sensor - msg.data[3] has the distance value
        self.gripper_sub = self.create_subscription(Int16MultiArray,
                                                    'microROS/sensor_data',
                                                    self.gripper_data_callback,
                                                    10)

        # which camera frame are we getting the point cloud from? (usually mast or down low one)
        self.source_frame = self.get_parameter("source_frame").value
                
        # End effector location, for generating point cloud image and fake data
        self.tf_buffer = Buffer()
        self.tf_listener = TransformListener(self.tf_buffer, self)
        
        # Listen for 3D marker locations. These will be projected into the image and published as another set of points
        #  at the same time as the new image comes in
        self.create_subscription(PoseArray, "apple_poses", self.apple_poses_callback, 10)

        # Keep the 3D centers and publish them whenever there's a new image
        self.apple_locs_3d: np.array = None
        self.apple_loc_pub = self.create_publisher(PoseArray, "gripper/apple_locs", qos_profile=qos_profile)

        # If there is a point cloud published, grab it
        self.create_subscription(PointCloud2, '/rgbd_pointcloud', self.pointcloud_callback, 10)

        # Keep the last pose so we don't reproject if the arm hasn't moved/pointcloud hasn't changed
        #   - set this back to None if the point cloud or 3D points changes
        self.current_pose: TransformStamped = None
        # If there is a point cloud that we're projecting from this camera viewpoint...
        self.point_cloud: PointCloud2 = None
        #  This is saved every time we project the point cloud, and is used to fake the depth data
        self.depth_point_cloud: np.array = None

        # Publish TOF info (real or fake) as a float
        self.tof_pub = self.create_publisher(Range, '/gripper/tof', 10)

        # camera setup
        if self.get_parameter('use_fake_hardware').value:
            # This is for producing the 3d point cloud projected image and (if fake hardware) also generating the fake camera image
            timer_hz = 1.0 / self.get_parameter('target_frame_rate').value
            self.get_logger().info(f"Setting callback rate as {timer_hz}")
            self.fake_image_timer = self.create_timer(timer_hz, self.fake_image_timer_callback)
            # Publish fake camera info - needed for visual servo (needs the k matrix)
            self.cam_info_pub = self.create_publisher(CameraInfo, '/gripper/rgb_palm_camera/camera_info', 2)

            self.resolution = resolution
            focal = 0.5 * (resolution[0] + resolution[1])
            self.fx = focal  # Focal length X - square pixels
            self.fy = focal  # Focal length Y
            self.cx = resolution[0] / 2.0
            self.cy = resolution[1] / 2.0
            self.get_logger().info(f"Started virtual camera, resolution {resolution} {self.fx}, {self.fy}")
            self.published_camera_info = False
            self.tof_exists = False
        else:
            camera_setup_result = self.create_camera()
            if not camera_setup_result:
                self.get_logger().error("Failed to setup camera with device number: {0}".format(self.device)) 
            else:
                self.get_logger().info("Succesfully setup camera with device number: {0}".format(self.device)) 
            # Note that the time of flight data is generated by a micro service running on the gripper chip itself
            self.tof_exists = self.create_tof()
            if not self.tof_exists:
                self.get_logger().error("Failed to find time of flight sensor")
            else:
                self.get_logger.info("Successfully setup time of flight sensor")

    # ================================================================== Initialize real data
    def create_camera(self):
        """ See if there's a real camera out there on the gripper """
        try: 
            self.camera = cv2.VideoCapture(self.device, cv2.CAP_V4L2)
            self.camera.set(cv2.CAP_PROP_FRAME_WIDTH, self.get_parameter('resolution')[0])
            self.camera.set(cv2.CAP_PROP_FRAME_HEIGHT, self.get_parameter('resolution')[1])
            self.camera.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc('M', 'J', 'P', 'G'))
            self.camera.set(cv2.CAP_PROP_FPS, self.get_parameter('target_frame_rate').value)
            return True
        except:
            return False

    def create_tof(self):
        """ TODO See if the micro node broadcasting tof is out there, get min/max range etc"""
        try:
            return True
        except:
            return False

    def start_gripper_camera_publisher(self):
        """ Publishes the real camera, and (if point cloud and/or apple loc exists) 
           - pointcloud projected image, 
           - 2D projected points
           - fake depth value (if no time of flight) """
        if self.camera is None:
            return
        try:
            while rclpy.ok():
                ret, frame = self.camera.read()
                image = frame
                if ret:
                    img_msg = self.bridge.cv2_to_imgmsg(image, "bgr8")
                    img_msg.header.stamp = self.get_clock().now().to_msg()
                    img_msg.header.frame_id = "gripper_palm_camera_optical_link"
                    self.camera_pub.publish(img_msg)
                    self._publish_additional_data(header=img_msg.header, pose_header=img_msg.header)

                    _, self.current_pose = self._get_current_pose(img_msg.header)
        except KeyboardInterrupt:
            return
        cv2.destroyAllWindows()
        self.camera.release()

    # ================================================================== Subscription callbacks
    def gripper_data_callback(self, msg: Int16MultiArray):
        """ Get the data from the actual tof on the gripper and publish as a float in meters"""
        depth_data = msg.data[3]   # Int In millimeters

        msg_tof = Range()
        msg_tof.header.stamp = self.get_clock().now().to_msg()
        msg_tof.header.frame_id = "gripper_palm_camera_optical_link"
        msg_tof.field_of_view = self.tof_angle
        msg_tof.range = float(depth_data * 100.0)  # Convert to meters
        self.tof_pub.publish(msg=msg_tof)

    def apple_poses_callback(self, msg: PoseArray):
        """ Get the markers from the 3D apple prediction and save them into the image"""
        self.apple_locs_3d = np.ones((len(msg.poses), 4))
        # Copy pose data in
        for indx, pose in enumerate(msg.poses):
            self.apple_locs_3d[0, indx] = pose.position.x
            self.apple_locs_3d[1, indx] = pose.position.y
            self.apple_locs_3d[2, indx] = pose.position.z
        self.current_pose = None

    def pointcloud_callback(self, msg):
        """ Grab the point cloud then call the rendermethod """

        self.get_logger().info(f"Getting point cloud")

        points = []
        colors = []
        indx = 0
        for point in pc2.read_points(msg, field_names=("x", "y", "z", "rgb"), skip_nans=True):
            x, y, z, rgb_packed = point
            points.append((x, y, z))

            # Re-interpret float32 color bits as uint32 - note, don't do this if the rgb is a packed integer
            # s = struct.pack('f', rgb_packed)
            # pack = struct.unpack('I', s)[0]
        
            # Unpack individual channels (0 to 255)
            r = (rgb_packed >> 16) & 0x00FF
            g = (rgb_packed >> 8) & 0x00FF
            b = rgb_packed & 0x00FF
            colors.append((r, g, b))
            indx += 1

        self.point_cloud = {"points": np.ones((4, len(points))), "colors": np.array(colors)}
        self.point_cloud["points"][0:3, :] = np.array(points).transpose()
        self.current_pose = None

    # ================================================================== End effector pose routines
    @staticmethod
    def _is_transform_equivalent(t1: TransformStamped, t2: TransformStamped, tol=1e-3) -> bool:
        """
        Returns True if translation and rotation values match within a tight tolerance.
        """
        p1, p2 = t1.transform.translation, t2.transform.translation
        r1, r2 = t1.transform.rotation, t2.transform.rotation
        
        # Check spatial position
        pos_match = (np.isclose(p1.x, p2.x, atol=tol) and
                     np.isclose(p1.y, p2.y, atol=tol) and
                     np.isclose(p1.z, p2.z, atol=tol))
                    
        # Check orientation quaternion
        rot_match = (np.isclose(r1.x, r2.x, atol=tol) and
                     np.isclose(r1.y, r2.y, atol=tol) and
                     np.isclose(r1.z, r2.z, atol=tol) and
                     np.isclose(r1.w, r2.w, atol=tol))
                    
        return pos_match and rot_match

    def _get_current_pose(self, header: Header):
        """ Sets current pose and returns True if the pose has changed from the last one saved
        Pass in time stamp so projected image is at the current time stamp"""
        to_frame = self.source_frame
        from_frame = 'gripper_palm_camera_optical_link'

        try:
            if header is not None:
                new_pose = self.tf_buffer.lookup_transform(from_frame, to_frame, 
                                                        time=header.stamp,
                                                        timeout=rclpy.duration.Duration(seconds=0.1))
            else:
                # Get closest time
                new_pose = self.tf_buffer.lookup_transform(from_frame, to_frame, 
                                                        time=rclpy.time.Time(),
                                                        timeout=rclpy.duration.Duration(seconds=0.1))

            b_changed = False
            if self.current_pose != None:
                if not self._is_transform_equivalent(new_pose, self.current_pose):
                    b_changed = True
            else:
                b_changed = True

            if b_changed:
                p = new_pose.transform.translation
                r = new_pose.transform.rotation
                self.get_logger().info(f"Pose changed {p.x:0.2f} {p.y:0.2f} {p.z:0.2f} {r.w:0.2f}")

            return b_changed, new_pose

        except TransformException as ex:
            self.get_logger().info(f'Could not transform {to_frame} to {from_frame}: {ex}')

        return False, None

    # ================================================================== Publish routines
    def _get_matrix_transform(self, pose):
        """Get the current mast to gripper camera matrix"""
        if pose == None:
            return np.identity(4)
        
        # Extract translation
        t = pose.transform.translation
        q = pose.transform.rotation

        # 2. Build the 3x3 rotation matrix (SciPy expects [x, y, z, w])
        rotation = R.from_quat([q.x, q.y, q.z, q.w])
        rotation_matrix_3x3 = rotation.as_matrix()

        # 3. Assemble the 4x4 homogeneous transformation matrix
        homogeneous_matrix = np.eye(4)
        homogeneous_matrix[0:3, 0:3] = rotation_matrix_3x3
        homogeneous_matrix[0:3, 3] = [t.x, t.y, t.z]
        return homogeneous_matrix

    def _publish_projection_image(self, header: Header, pose_header: Header):
        """ Publish both the point cloud projected to this camera (if available) and the 3D points projected to this camera"""
        if self.point_cloud is None:
            return

        b_changed, new_pose = self._get_current_pose(pose_header)
        if b_changed == False:
            return
        
        self.get_logger().info(f"Rendering point cloud {self.resolution}, N points {self.point_cloud['points'].shape}, {self.point_cloud['colors'].shape}")

        # image - width and height
        img = np.zeros((self.resolution[1], self.resolution[0], 3), dtype=np.uint8)

        # Iterate through points
        # Move the points
        homogeneous_matrix = self._get_matrix_transform(new_pose)
        points_transformed = (homogeneous_matrix @ self.point_cloud["points"]).transpose()

        # Merge the points with the colors for the following operations (nx7 matrix)
        points_and_colors = np.hstack((points_transformed[:, 0:3], self.point_cloud["colors"]))
        
        # Filter on depth
        valid_mask = points_and_colors[:, 2] > 0.01
        points_and_colors_keep = points_and_colors[valid_mask, :]
        
        # Sort by depth
        points_sorted = points_and_colors_keep[(-points_and_colors_keep[:, 2]).argsort()]

        # Transform to image coordinates
        x, y, self.depth_point_cloud = points_sorted[:, 0], points_sorted[:, 1], points_sorted[:, 2]

        u = (x * self.fx / self.depth_point_cloud) + self.cx
        v = (y * self.fy / self.depth_point_cloud) + self.cy

        # Trim again, this time for u,v out of bounds
        valid_pixels = (u >= 0) & (u < self.resolution[0]) & (v >= 0) & (v < self.resolution[1])

        # Convert to ints for indexing
        u_idx = u[valid_pixels].astype(int)
        v_idx = v[valid_pixels].astype(int)

        colors = points_sorted[valid_pixels, 3:]
        for indx in range(len(u_idx)):
            # Colors for each pixel
            rgb_pix = colors[indx, :]
            # b g r
            img[v_idx[indx], u_idx[indx]] = [rgb_pix[2], rgb_pix[1], rgb_pix[0]]

        # 6. Publish the image and info messages        
        cv2.imwrite('check.png', img)
        img_msg = self.bridge.cv2_to_imgmsg(img, encoding="bgr8")

        img_msg.header = header
        img_msg.header.frame_id = "gripper_palm_camera_optical_link"
        self.proj_im_pub.publish(img_msg)

        if self.get_parameter('use_fake_hardware').value:
            if not self.published_camera_info:
                info_msg = CameraInfo()
                info_msg.header.stamp = self.get_clock().now().to_msg()
                info_msg.header.frame_id = "gripper_palm_camera_optical_link"
                info_msg.width = self.resolution[0]
                info_msg.height = self.resolution[1]
                info_msg.k = [self.fx, 0.0, self.cx, 0.0, self.fy, self.cy, 0.0, 0.0, 1.0]
                self.cam_info_pub.publish(info_msg)

            # And the fake image
            self.camera_pub.publish(img_msg)
            self.published_camera_info = True

        self.get_logger().info("Done")

    def _publish_projected_pts(self, header: Header, pose_header: Header):
        """ Get the markers from the 3D apple prediction and project them into the image"""
        if not self.apple_locs_3d:
            return

        b_changed, new_pose = self._get_current_pose(pose_header)
        if b_changed == False:
            return
        
        self.get_logger().info(f"Projecting points into image")

        homogeneous_matrix = self._get_matrix_transform(new_pose)

        pa = PoseArray()
        pa.header = header

        # Project all of the points, even if they end up behind the camera
        pts_proj = homogeneous_matrix @ self.apple_locs_3d
        for col_indx in range(0, pts_proj.shape[1]):
            pt_in_image = pts_proj[:, col_indx]
            x = pt_in_image[0]
            y = pt_in_image[1]
            z = pt_in_image[2]

            u = (x * self.fx / z) + self.cx
            v = (y * self.fy / z) + self.cy
            
            proj_pt = Pose()
            proj_pt.position.x    = float(u)
            proj_pt.position.y    = float(v)
            proj_pt.position.z    = float(z)
            proj_pt.orientation.w = 1.0

            pa.poses.append(proj_pt)

        self.get_logger().info(f"Publishing {len(pa.poses)} projected apple locations")
        self.apple_loc_pub.publish(pa)

    def _publish_fake_tof(self, header: Header):
        """ If there is a point cloud, take the average depth of points in the middle"""
        if self.depth_point_cloud is None:
            return

        # what part of the depth image to use
        # theta = arctan((u - cx) / fx)
        #  u = fx * tan(theta) + cx
        x_lim = int(self.fx * np.tan(self.tof_angle / 2.0) + self.cx)
        y_lim = int(self.fy * np.tan(self.tof_angle / 2.0) + self.cy)
        self.get_logger().info(f"Getting middle of image {x_lim} {y_lim} {self.depth_point_cloud.shape}")
        x_lim = np.min(x_lim, self.depth_point_cloud.shape[1] // 2)
        y_lim = np.min(y_lim, self.depth_point_cloud.shape[0] // 2)
        z = np.mean(self.depth_point_cloud[self.cy - y_lim:self.cy + y_lim, self.cx - x_lim:self.cx + x_lim])

        msg_tof = Range()
        msg_tof.header = header
        msg_tof.field_of_view = self.tof_angle
        msg_tof.range = z
        self.tof_pub.publish(msg_tof)

    def _publish_additional_data(self, header: Header, pose_header: Header = None):
        if self.point_cloud is not None:
            self._publish_projection_image(header, pose_header)
            if not self.tof_exists:
                self._publish_fake_tof(header)
        if self.apple_locs_3d is not None:
            self._publish_projected_pts(header, pose_header)

    # ================================================================== Fake hardware routines
    def fake_image_timer_callback(self):
        header = Header()
        header.frame_id = self.source_frame
        header.stamp = self.get_clock().now().to_msg()

        _, new_pose = self._get_current_pose(header=None)
        # Note - if fake hardware is true, this will also publish the fake image
        self._publish_additional_data(header=header, pose_header=None)

        self.current_pose = new_pose


def main(args=None):
    rclpy.init(args=args)
    camera_publisher = GripperPalmCamera()
    camera_publisher.start_gripper_camera_publisher()
    rclpy.spin(camera_publisher)
    rclpy.shutdown()


if __name__ == '__main__':
    main()
